package model

import "time"

// User represents a registered bot user.
type User struct {
	UserID    int64
	CreatedAt time.Time
}

// Meeting represents a transcribed audio/voice file stored in the database.
type Meeting struct {
	ID         string // UUID generated by PostgreSQL
	UserID     int64
	FileID     string
	Transcript string
	Summary    string // short Russian summary from GigaChat (optional)
	CreatedAt  time.Time
}
